### ISSUE TITLE
Ventanas incomodas

### ISSUE THREAD

**Issue by SiteGames** [tronicStart/charDeveloping#13]
## Descripción del problema o mejora

Aunque la interfaz actual es aceptable o buena las otras ventanas no. Me refiero a que las ventanas de habrir archivo, borrar son muy poco intuitivas y incomodas de manejar aveces nose cuando presionar enter o con el mouse.

## Cómo reproducir el problema (si es aplicable)

Ninguno

## Capturas de pantalla o archivos adjuntos (si es aplicable)

No es necesario

## Solución propuesta (si es aplicable)

¡Claro! Agregar botones y texto a las otras ventanas para que sea mas comodo

## Información adicional (si es aplicable)

Nada.

**Comment by SinCorreo1910** [comment]
No cree otros issues con el mismo problema vaya a #11 donde se habla de esto.
